import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { imageUrl, tmdb } from './services/tmdb';
import type { Genre, Page } from './services/tmdb';
import { isSupabaseConfigured, requireSupabase } from './services/supabase';
import { registerUser, signInUser, updateUser } from './services/users';
import type { ApiUser } from './services/users';
import type { Movie, MovieStatus, UserMovie, Watchlist } from './types';
import './App.css';

const AuthContext = createContext<{ user: ApiUser | null; ready: boolean; refresh: () => void }>({ user: null, ready: false, refresh: () => {} });
const useAuth = () => useContext(AuthContext);
const statusLabel: Record<MovieStatus, string> = { planned: 'Planuoju žiūrėti', watching: 'Žiūriu dabar', watched: 'Peržiūrėta' };

function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<ApiUser | null>(null); const [ready, setReady] = useState(false); const [version, setVersion] = useState(0);
  useEffect(() => {
    try {
      const saved = sessionStorage.getItem('kinolog-user');
      setUser(saved ? JSON.parse(saved) as ApiUser : null);
    } catch {
      sessionStorage.removeItem('kinolog-user');
    } finally {
      setReady(true);
    }
  }, [version]);
  return <AuthContext.Provider value={{ user, ready, refresh: () => setVersion(v => v + 1) }}>{children}</AuthContext.Provider>;
}

function useLoad<T>(loader: (signal: AbortSignal) => Promise<T>, deps: unknown[] = []) {
  const [data, setData] = useState<T | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [again, setAgain] = useState(0);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); loader(controller.signal).then(v => { if (!controller.signal.aborted) setData(v); }).catch(e => { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Įvyko klaida.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [...deps, again]);
  return { data, loading, error, retry: () => setAgain(x => x + 1) };
}
function State({ loading, error, retry, children }: { loading?: boolean; error?: string; retry?: () => void; children?: ReactNode }) {
  if (loading) return <div className="state"><span className="spinner" />Kraunami filmai…</div>;
  if (error) return <div className="state error-state"><p>{error}</p>{retry && <button className="button secondary" onClick={retry}>Bandyti dar kartą</button>}</div>;
  return <>{children}</>;
}
function Poster({ movie, size = 'w500' }: { movie: Movie; size?: string }) {
  const src = imageUrl(movie.poster_path, size);
  return src ? <img className="poster" src={src} alt={`${movie.title} plakatas`} loading="lazy" /> : <div className="poster poster-fallback" aria-label="Plakato nėra"><span>🎞</span><small>{movie.title}</small></div>;
}
function MovieCard({ movie, compact = false }: { movie: Movie; compact?: boolean }) {
  return <Link to={`/movie/${movie.id}`} className={`movie-card${compact ? ' compact' : ''}`}><div className="poster-wrap"><Poster movie={movie} /><span className="score">★ {movie.vote_average?.toFixed(1) || '—'}</span></div><h3>{movie.title}</h3><p>{movie.release_date?.slice(0, 4) || 'Metai nenurodyti'}</p></Link>;
}
function MovieGrid({ movies, compact = false }: { movies: Movie[]; compact?: boolean }) { return <div className={`movie-grid${compact ? ' compact-grid' : ''}`}>{movies.map(m => <MovieCard key={m.id} movie={m} compact={compact} />)}</div>; }
function Header() {
  const { user } = useAuth(); const [query, setQuery] = useState(''); const nav = useNavigate();
  const search = (e: FormEvent) => { e.preventDefault(); nav(`/discover${query ? `?q=${encodeURIComponent(query)}` : ''}`); };
  function logout() { sessionStorage.removeItem('kinolog-user'); window.location.assign('/'); }
  return <header className="topbar"><div className="nav-inner"><Link to="/" className="brand"><span className="brand-mark">K</span>Kino<span>Log</span></Link><nav className="main-nav"><NavLink to="/" end>Pagrindinis</NavLink><NavLink to="/discover">Atrask filmus</NavLink><NavLink to="/library">Mano filmai</NavLink><NavLink to="/lists">Mano sąrašai</NavLink></nav><form className="nav-search" onSubmit={search}><span>⌕</span><input aria-label="Ieškoti filmų" placeholder="Ieškoti filmų…" value={query} onChange={e => setQuery(e.target.value)} /><button aria-label="Ieškoti">↵</button></form><div className="user-nav">{user ? <><Link to={`/profile/${user.username}`} className="avatar">{user.username.slice(0,1).toUpperCase()}</Link><Link to="/account" className="text-button">Paskyra</Link><button onClick={logout} className="text-button">Atsijungti</button></> : <Link className="button small" to="/login">Prisijungti</Link>}</div></div></header>;
}
function Home() {
  const popular = useLoad(s => tmdb.popular(1).then(x => x.results), []); const top = useLoad(s => tmdb.topRated(1).then(x => x.results), []); const now = useLoad(s => tmdb.nowPlaying(1).then(x => x.results), []);
  const hero = popular.data?.[0]; const backdrop = hero && imageUrl(hero.backdrop_path, 'original');
  return <main><section className="hero" style={backdrop ? { backgroundImage: `linear-gradient(90deg, #111 0%, rgba(17,17,17,.92) 28%, rgba(17,17,17,.35) 75%, rgba(17,17,17,.4)), linear-gradient(0deg,#111 0%,transparent 45%), url(${backdrop})` } : undefined}><div className="hero-copy"><span className="eyebrow">KINOLOG • FILMŲ ŽURNALAS</span>{hero ? <><h1>{hero.title}</h1><div className="hero-meta"><span>{hero.release_date?.slice(0,4)}</span><span>★ {hero.vote_average.toFixed(1)} TMDB</span></div><p>{hero.overview || 'Atraskite šį filmą ir įtraukite į savo asmeninę kolekciją.'}</p><div className="actions"><Link className="button" to={`/movie/${hero.id}`}>▶ Peržiūrėti filmą</Link><Link className="button secondary" to={`/movie/${hero.id}`}>＋ Pridėti į sąrašą</Link></div></> : <State loading={popular.loading} error={popular.error} retry={popular.retry} />}</div></section><div className="page-content"><MovieSection title="Šiuo metu populiaru" subtitle="Filmai, apie kuriuos kalba visi" state={popular} /><MovieSection title="Geriausiai įvertinti" subtitle="Žiūrovų pamėgti filmai" state={top} /><MovieSection title="Dabar kino teatruose" subtitle="Naujausi kino atradimai" state={now} /><PublicLists /></div><Attribution /></main>;
}
function MovieSection({ title, subtitle, state }: { title: string; subtitle: string; state: ReturnType<typeof useLoad<Movie[]>> }) { return <section className="section"><div className="section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><Link to="/discover">Žiūrėti visus →</Link></div><State loading={state.loading} error={state.error} retry={state.retry}>{state.data && <MovieGrid movies={state.data.slice(0, 6)} />}</State></section>; }
function Discover() {
  const [params, setParams] = useSearchParams(); const [query, setQuery] = useState(params.get('q') || ''); const [debounced, setDebounced] = useState(query); const [genre, setGenre] = useState(''); const [year, setYear] = useState(''); const [sort, setSort] = useState('popularity.desc'); const [page, setPage] = useState(1);
  useEffect(() => { const id = window.setTimeout(() => { setDebounced(query); setPage(1); }, 350); return () => window.clearTimeout(id); }, [query]);
  useEffect(() => { setQuery(params.get('q') || ''); }, [params]);
  const result = useLoad<Page<Movie>>(s => tmdb.discover({ query: debounced, page, genre, year, sort }, s), [debounced, page, genre, year, sort]);
  const genres = useLoad<Genre[]>(() => tmdb.genres().then(x => x.genres), []);
  return <main className="page-content inner-page"><div className="page-title"><span className="eyebrow">FILMŲ KATALOGAS</span><h1>Atrask savo kitą filmą</h1><p>Ieškok, filtruok ir kurk savo kino kolekciją.</p></div><div className="filters"><label className="field search-field">Paieška<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filmo pavadinimas…" /></label><label className="field">Žanras<select value={genre} onChange={e => setGenre(e.target.value)}><option value="">Visi žanrai</option>{genres.data?.map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="field">Metai<input type="number" min="1870" max="2100" value={year} onChange={e => setYear(e.target.value)} placeholder="2024" /></label><label className="field">Rikiuoti<select value={sort} onChange={e => setSort(e.target.value)}><option value="popularity.desc">Populiarumas</option><option value="vote_average.desc">TMDB įvertinimas</option><option value="primary_release_date.desc">Išleidimo data</option></select></label></div><State loading={result.loading} error={result.error} retry={result.retry}>{result.data?.results.length ? <><MovieGrid movies={result.data.results} /><div className="pagination"><button className="button secondary" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>← Atgal</button><span>{page} / {Math.max(result.data.total_pages,1)}</span><button className="button secondary" disabled={page >= Math.min(result.data.total_pages,500)} onClick={() => setPage(p => p + 1)}>Toliau →</button></div></> : <div className="empty"><span>⌕</span><h3>Filmų nerasta</h3><p>Pabandyk kitą pavadinimą arba pakeisk filtrus.</p></div>}</State><Attribution /></main>;
}
function Login() {
  const { user, refresh } = useAuth(); const nav = useNavigate(); const [register, setRegister] = useState(location.pathname === '/register'); const [password, setPassword] = useState(''); const [username, setUsername] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => setRegister(location.pathname === '/register'), [location.pathname]);
  const returnTo = new URLSearchParams(location.search).get('redirect');
  const safeReturnTo = returnTo?.startsWith('/') && !returnTo.startsWith('//') ? returnTo : '/library';
  useEffect(() => { if (user) nav(safeReturnTo, { replace: true }); }, [user, nav, safeReturnTo]);
  async function submit(e: FormEvent) { e.preventDefault(); if (!register && !user) return; setMessage(''); if (password.length < 8) { setMessage('Slaptažodis turi būti bent 8 simbolių.'); return; } if (!/^[a-z0-9_]{3,24}$/i.test(username.trim())) { setMessage('Vardas: 3–24 simboliai, raidės, skaičiai ir _.'); return; } setBusy(true); try { const account = register ? await registerUser(username.trim(), password) : await signInUser(username.trim(), password); sessionStorage.setItem('kinolog-user', JSON.stringify(account)); refresh(); nav(safeReturnTo); } catch (e) { setMessage(e instanceof Error ? e.message : 'Nepavyko. Bandykite dar kartą.'); } finally { setBusy(false); } }
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><Link className="brand" to="/"><span className="brand-mark">K</span>Kino<span>Log</span></Link><h1>{register ? 'Sukurk paskyrą' : 'Sugrįžk į KinoLog'}</h1><p>{register ? 'Kurk kolekciją. Atrask istorijas.' : 'Tavo filmų kolekcija laukia.'}</p><label className="field">Vartotojo vardas<input autoComplete="username" required minLength={3} maxLength={24} value={username} onChange={e => setUsername(e.target.value)} /></label><label className="field">Slaptažodis<input type="password" autoComplete={register ? 'new-password' : 'current-password'} minLength={8} required value={password} onChange={e => setPassword(e.target.value)} /></label>{message && <p className="form-message" role="alert">{message}</p>}<button className="button full" disabled={busy}>{busy ? 'Prašome palaukti…' : register ? 'Sukurti paskyrą' : 'Prisijungti'}</button><p className="switch-auth">{register ? 'Jau turi paskyrą?' : 'Dar neturi paskyros?'} <button type="button" className="link-button" onClick={() => { setRegister(!register); setMessage(''); nav(register ? '/login' : '/register'); }}>{register ? 'Prisijunk' : 'Registruokis'}</button></p></form></main>;
}
function AccountSettings() {
  const { user, refresh } = useAuth(); const [username, setUsername] = useState(user?.username || ''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [success, setSuccess] = useState(false);
  useEffect(() => setUsername(user?.username || ''), [user]);
  if (!user) return <SignInPrompt title="Paskyros nustatymai" text="Prisijunk, kad galėtum atnaujinti paskyros duomenis." />;
  async function submit(e: FormEvent) { e.preventDefault(); if (!user) return; setMessage(''); setSuccess(false); const nextUsername = username.trim(); if (!/^[a-z0-9_]{3,24}$/i.test(nextUsername)) { setMessage('Vardas: 3–24 simboliai, raidės, skaičiai ir _.'); return; } if (password && password.length < 8) { setMessage('Slaptažodis turi būti bent 8 simbolių.'); return; } const changes: { username?: string; password?: string } = {}; if (nextUsername !== user.username) changes.username = nextUsername; if (password) changes.password = password; if (!Object.keys(changes).length) { setMessage('Pakeitimų nėra.'); return; } setBusy(true); try { const updated = await updateUser(user.id, changes); sessionStorage.setItem('kinolog-user', JSON.stringify(updated)); setUsername(updated.username); setPassword(''); setSuccess(true); setMessage('Paskyros duomenys atnaujinti.'); refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Nepavyko atnaujinti paskyros.'); } finally { setBusy(false); } }
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><span className="eyebrow">PASKYROS NUSTATYMAI</span><h1>Atnaujink duomenis</h1><p>Keisk vartotojo vardą arba slaptažodį.</p><label className="field">Vartotojo vardas<input autoComplete="username" required minLength={3} maxLength={24} value={username} onChange={e => setUsername(e.target.value)} /></label><label className="field">Naujas slaptažodis<input type="password" autoComplete="new-password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} placeholder="Palik tuščią, jei nekeiti" /></label>{message && <p className={`form-message${success ? ' form-success' : ''}`} role="status">{message}</p>}<button className="button full" disabled={busy}>{busy ? 'Atnaujinama…' : 'Išsaugoti pakeitimus'}</button></form></main>;
}
function MovieDetails() {
  const { id } = useParams(); const movieId = Number(id); const { user } = useAuth(); const [record, setRecord] = useState<UserMovie | null>(null); const [rating, setRating] = useState(''); const [review, setReview] = useState(''); const [isPublic, setIsPublic] = useState(true); const [status, setStatus] = useState<MovieStatus>('planned'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const details = useLoad<Movie>(s => tmdb.movie(movieId, s), [movieId]);
  useEffect(() => { if (!user || !isSupabaseConfigured || !Number.isInteger(movieId)) { setRecord(null); return; } let live = true; requireSupabase().from('user_movies').select('*').eq('user_id', String(user.id)).eq('tmdb_movie_id', movieId).maybeSingle().then(({ data }) => { if (live) { const r = data as UserMovie | null; setRecord(r); setRating(r?.rating ? String(r.rating) : ''); setReview(r?.review || ''); setStatus(r?.status || 'planned'); setIsPublic(r?.is_public ?? true); } }, () => {}); return () => { live = false; }; }, [user, movieId]);
  async function save(e: FormEvent) { e.preventDefault(); if (!user) { location.href = `/login?redirect=${encodeURIComponent(location.pathname)}`; return; } if (!isSupabaseConfigured) { setMessage('Filmų biblioteka dar neprijungta. Nustatykite Supabase URL ir viešą raktą.'); return; } if (rating && (!Number.isInteger(Number(rating)) || Number(rating) < 1 || Number(rating) > 10)) { setMessage('Įvertinimas turi būti nuo 1 iki 10.'); return; } setBusy(true); setMessage(''); try { const payload = { user_id: String(user.id), tmdb_movie_id: movieId, status, rating: rating ? Number(rating) : null, review: review.trim() || null, is_public: isPublic, watched_at: status === 'watched' ? new Date().toISOString() : null }; const { data, error } = await requireSupabase().from('user_movies').upsert(payload, { onConflict: 'user_id,tmdb_movie_id' }).select().single(); if (error) throw error; setRecord(data as UserMovie); setMessage('Pakeitimai išsaugoti.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Nepavyko išsaugoti.'); } finally { setBusy(false); } }
  const m = details.data; const backdrop = m && imageUrl(m.backdrop_path, 'original');
  return <main><State loading={details.loading} error={details.error} retry={details.retry}>{m && <><section className="detail-hero" style={backdrop ? { backgroundImage: `linear-gradient(90deg,#111 4%,rgba(17,17,17,.86) 45%,rgba(17,17,17,.35)),linear-gradient(0deg,#111,transparent 65%),url(${backdrop})` } : undefined}><div className="detail-inner"><Poster movie={m} /><div className="detail-copy"><span className="eyebrow">FILMO DUOMENYS</span><h1>{m.title}</h1>{m.original_title !== m.title && <p className="original-title">{m.original_title}</p>}<div className="hero-meta"><span>{m.release_date || 'Data nenurodyta'}</span>{m.runtime && <span>{m.runtime} min.</span>}<span>★ {m.vote_average.toFixed(1)} TMDB · {m.vote_count?.toLocaleString('lt-LT')} balsų</span></div><div className="genre-tags">{m.genres?.map(g => <span key={g.id}>{g.name}</span>)}</div><p className="overview">{m.overview || 'Aprašymo nėra.'}</p><p className="tmdb-note">TMDB bendruomenės įvertinimas skiriasi nuo tavo asmeninio įvertinimo.</p></div></div></section><section className="page-content detail-form"><form onSubmit={save} className="review-card"><div><span className="eyebrow">TAVO KOLEKCIJA</span><h2>{record ? 'Atnaujink savo įrašą' : 'Pridėk filmą į biblioteką'}</h2></div><label className="field">Žiūrėjimo būsena<select value={status} onChange={e => setStatus(e.target.value as MovieStatus)}><option value="planned">Planuoju žiūrėti</option><option value="watching">Žiūriu dabar</option><option value="watched">Peržiūrėta</option></select></label><label className="field">Asmeninis įvertinimas (1–10)<input type="number" min="1" max="10" value={rating} onChange={e => setRating(e.target.value)} placeholder="—" /></label><label className="field">Atsiliepimas<textarea value={review} onChange={e => setReview(e.target.value)} maxLength={3000} rows={4} placeholder="Ką manai apie šį filmą?" /></label><label className="visibility-field"><input type="checkbox" checked={isPublic} onChange={e => setIsPublic(e.target.checked)} /> Viešai rodyti mano įvertinimą, atsiliepimą ir filmo istoriją</label>{message && <p className="form-message" role="status">{message}</p>}<button className="button" disabled={busy}>{busy ? 'Saugoma…' : record ? 'Išsaugoti pakeitimus' : 'Pridėti į biblioteką'}</button></form><Reviews movieId={movieId} ownId={user ? String(user.id) : undefined} /></section></>}</State><Attribution /></main>;
}
function Reviews({ movieId, ownId }: { movieId: number; ownId?: string }) { const [rows, setRows] = useState<(UserMovie & { profiles?: { username: string; display_name: string | null } })[]>([]); useEffect(() => { if (!isSupabaseConfigured) return; let live = true; requireSupabase().from('user_movies').select('*, profiles(username, display_name)').eq('tmdb_movie_id', movieId).eq('is_public', true).not('review', 'is', null).order('updated_at', { ascending: false }).then(({ data }) => { if (live && data) setRows(data as typeof rows); }); return () => { live = false; }; }, [movieId]); const others = rows.filter(r => r.user_id !== ownId); return <div className="reviews"><h2>Žiūrovų atsiliepimai</h2>{others.length ? others.map(r => <article className="review-row" key={r.id}><strong>{r.profiles?.display_name || r.profiles?.username || 'Kino žiūrovas'} <span>★ {r.rating ?? '—'}/10</span></strong><p>{r.review}</p></article>) : <p className="muted">Kol kas viešų atsiliepimų nėra.</p>}</div>; }
function Library() {
  const { user } = useAuth(); const [items, setItems] = useState<UserMovie[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [status, setStatus] = useState('all'); const [sort, setSort] = useState('created_at'); const [version, setVersion] = useState(0);
  useEffect(() => { if (!user) { setLoading(false); return; } let live = true; setLoading(true); (async () => { try { let q = requireSupabase().from('user_movies').select('*').eq('user_id', user.id); if (status !== 'all') q = q.eq('status', status); const { data, error: e } = await (sort === 'title' ? q.order('created_at') : q.order(sort, { ascending: sort === 'created_at' })); if (e) throw e; const rows = (data || []) as UserMovie[]; const movies = await Promise.all(rows.map(async r => { try { return { ...r, movie: await tmdb.movie(r.tmdb_movie_id) }; } catch { return r; } })); if (live) setItems(sort === 'title' ? movies.sort((a,b) => (a.movie?.title || '').localeCompare(b.movie?.title || '', 'lt')) : movies); } catch (e) { if (live) setError(e instanceof Error ? e.message : 'Nepavyko įkelti bibliotekos.'); } finally { if (live) setLoading(false); } })(); return () => { live = false; }; }, [user, status, sort, version]);
  if (!user) return <SignInPrompt title="Tavo filmų kolekcija" text="Prisijunk, kad išsaugotum filmus, įvertinimus ir atsiliepimus." />;
  async function remove(id: string) { if (!window.confirm('Pašalinti filmą iš bibliotekos?')) return; const { error: e } = await requireSupabase().from('user_movies').delete().eq('id', id); if (e) setError(e.message); else setVersion(v => v + 1); }
  return <main className="page-content inner-page"><div className="page-title"><span className="eyebrow">ASMENINĖ KOLEKCIJA</span><h1>Mano filmai</h1><p>{items.length} filmai tavo kino istorijoje</p></div><div className="filters"><label className="field">Būsena<select value={status} onChange={e => setStatus(e.target.value)}><option value="all">Visi filmai</option><option value="planned">Planuoju žiūrėti</option><option value="watching">Žiūriu dabar</option><option value="watched">Peržiūrėta</option></select></label><label className="field">Rikiuoti<select value={sort} onChange={e => setSort(e.target.value)}><option value="created_at">Pridėjimo data</option><option value="rating">Įvertinimas</option><option value="title">Pavadinimas</option></select></label><Link className="button" to="/discover">＋ Atrasti filmus</Link></div><State loading={loading} error={error} retry={() => setVersion(v => v + 1)}>{items.length ? <div className="library-grid">{items.map(item => <article className="library-item" key={item.id}>{item.movie ? <MovieCard movie={item.movie} /> : <div className="poster poster-fallback">Filmas #{item.tmdb_movie_id}</div>}<div className="library-meta"><span className={`status-pill ${item.status}`}>{statusLabel[item.status]}</span><span>Asmeninis įvertinimas: {item.rating ?? '—'}/10</span>{item.review && <p>{item.review}</p>}<button className="text-button danger" onClick={() => remove(item.id)}>Pašalinti</button></div></article>)}</div> : <div className="empty"><span>▧</span><h3>Biblioteka dar tuščia</h3><p>Atrask filmų katalogą ir išsaugok mėgstamiausius.</p><Link className="button" to="/discover">Atrasti filmus</Link></div>}</State><Attribution /></main>;
}
function Lists() {
  const { user } = useAuth(); const [lists, setLists] = useState<Watchlist[]>([]); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [version, setVersion] = useState(0);
  useEffect(() => { if (!user || !isSupabaseConfigured) return; let live = true; requireSupabase().from('watchlists').select('*').eq('user_id', String(user.id)).order('created_at', { ascending: false }).then(({ data, error }) => { if (live) { if (error) setMessage(error.message); else setLists((data || []) as Watchlist[]); } }, e => { if (live) setMessage(e instanceof Error ? e.message : 'Nepavyko įkelti sąrašų.'); }); return () => { live = false; }; }, [user, version]);
  if (!user) return <SignInPrompt title="Mano sąrašai" text="Prisijunk ir kurk viešus filmų sąrašus, kuriais galėsi dalintis." />;
  async function create(e: FormEvent) { e.preventDefault(); if (!title.trim()) { setMessage('Įrašyk sąrašo pavadinimą.'); return; } setBusy(true); try { const { error } = await requireSupabase().from('watchlists').insert({ user_id: user!.id, title: title.trim(), description: description.trim() || null, is_public: true }); if (error) throw error; setTitle(''); setDescription(''); setMessage('Sąrašas sukurtas.'); setVersion(v => v + 1); } catch (e) { setMessage(e instanceof Error ? e.message : 'Nepavyko sukurti sąrašo.'); } finally { setBusy(false); } }
  async function remove(id: string) { if (!window.confirm('Ištrinti šį sąrašą?')) return; const { error } = await requireSupabase().from('watchlists').delete().eq('id', id); if (error) setMessage(error.message); else setVersion(v => v + 1); }
  return <main className="page-content inner-page"><div className="page-title"><span className="eyebrow">KURATORIŲ ATRANKA</span><h1>Mano sąrašai</h1><p>Sukurk teminius filmų sąrašus ir dalinkis jais viešai.</p></div><div className="lists-layout"><form className="review-card list-form" onSubmit={create}><h2>Naujas sąrašas</h2><label className="field">Pavadinimas<input required maxLength={80} value={title} onChange={e => setTitle(e.target.value)} placeholder="Pvz., Penktadienio klasika" /></label><label className="field">Aprašymas<textarea maxLength={500} rows={4} value={description} onChange={e => setDescription(e.target.value)} placeholder="Apie ką šis sąrašas?" /></label><p className="muted">Nauji sąrašai yra vieši.</p>{message && <p className="form-message" role="status">{message}</p>}<button className="button" disabled={busy}>{busy ? 'Kuriama…' : 'Sukurti sąrašą'}</button></form><section className="my-lists"><h2>Tavo sąrašai <span className="count">{lists.length}</span></h2>{lists.length ? lists.map(l => <article className="list-row" key={l.id}><div><h3><Link to={`/lists/${l.id}`}>{l.title}</Link></h3><p>{l.description || 'Aprašymo nėra.'}</p><small>Viešas · {new Date(l.created_at).toLocaleDateString('lt-LT')}</small></div><div><Link className="text-button" to={`/lists/${l.id}`}>Atidaryti →</Link><button className="text-button danger" onClick={() => remove(l.id)}>Ištrinti</button></div></article>) : <div className="empty small-empty"><p>Sąrašų dar nesukūrei.</p></div>}</section></div><PublicLists /><Attribution /></main>;
}
function PublicLists() { const [lists, setLists] = useState<(Watchlist & { profiles?: { username: string; display_name: string | null } })[]>([]); useEffect(() => { let live = true; if (!isSupabaseConfigured) return; requireSupabase().from('watchlists').select('*, profiles(username, display_name)').eq('is_public', true).order('created_at', { ascending: false }).limit(6).then(({ data }) => { if (live && data) setLists(data as typeof lists); }); return () => { live = false; }; }, []); if (!lists.length) return null; return <section className="section"><div className="section-heading"><div><h2>Bendruomenės sąrašai</h2><p>KinoLog bendruomenės atrinkti filmai</p></div></div><div className="public-lists">{lists.map(l => <Link className="public-list-card" to={`/lists/${l.id}`} key={l.id}><span className="list-icon">▤</span><h3>{l.title}</h3><p>{l.description || 'Atrinkti filmai KinoLog bendruomenei.'}</p><small>@{l.profiles?.username || 'kinomanas'}</small></Link>)}</div></section>; }
function ListDetail() {
  const { id } = useParams(); const { user } = useAuth(); const [list, setList] = useState<Watchlist | null>(null); const [movies, setMovies] = useState<Movie[]>([]); const [search, setSearch] = useState(''); const [results, setResults] = useState<Movie[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [version, setVersion] = useState(0); const [editing, setEditing] = useState(false); const [editTitle, setEditTitle] = useState(''); const [editDescription, setEditDescription] = useState('');
  useEffect(() => { let live = true; (async () => { try { const client = requireSupabase(); const { data, error } = await client.from('watchlists').select('*, profiles(username, display_name, avatar_url)').eq('id', id).single(); if (error) throw error; const l = data as Watchlist; const { data: rows, error: re } = await client.from('watchlist_movies').select('*').eq('watchlist_id', id).order('position'); if (re) throw re; const ms = await Promise.all((rows || []).map((r: { tmdb_movie_id: number }) => tmdb.movie(r.tmdb_movie_id))); if (live) { setList(l); setMovies(ms); setEditTitle(l.title); setEditDescription(l.description || ''); } } catch (e) { if (live) setMessage(e instanceof Error ? e.message : 'Sąrašas nerastas arba yra privatus.'); } })(); return () => { live = false; }; }, [id, version]);
  useEffect(() => { if (search.trim().length < 2) { setResults([]); return; } const c = new AbortController(); const t = window.setTimeout(() => tmdb.search(search, 1, c.signal).then(r => setResults(r.results.slice(0,5))).catch(() => {}), 300); return () => { clearTimeout(t); c.abort(); }; }, [search]);
  const owner = user && list?.user_id === user.id;
  async function saveList(e: FormEvent) { e.preventDefault(); if (!editTitle.trim()) { setMessage('Pavadinimas negali būti tuščias.'); return; } setBusy(true); const { error } = await requireSupabase().from('watchlists').update({ title: editTitle.trim(), description: editDescription.trim() || null }).eq('id', id); setBusy(false); if (error) setMessage(error.message); else { setEditing(false); setMessage('Sąrašo informacija išsaugota.'); setVersion(v => v + 1); } }
  async function add(movie: Movie) { if (!owner) return; setBusy(true); const { error } = await requireSupabase().from('watchlist_movies').insert({ watchlist_id: id, tmdb_movie_id: movie.id, position: movies.length }); setBusy(false); if (error) setMessage(error.message); else { setSearch(''); setResults([]); setVersion(v => v + 1); } }
  async function remove(movieId: number) { const { error } = await requireSupabase().from('watchlist_movies').delete().eq('watchlist_id', id).eq('tmdb_movie_id', movieId); if (error) setMessage(error.message); else setVersion(v => v + 1); }
  async function shift(i: number, offset: number) { const dest = i + offset; if (dest < 0 || dest >= movies.length) return; const a = movies[i], b = movies[dest]; const client = requireSupabase(); const { error } = await client.from('watchlist_movies').update({ position: dest }).eq('watchlist_id', id).eq('tmdb_movie_id', a.id); if (!error) await client.from('watchlist_movies').update({ position: i }).eq('watchlist_id', id).eq('tmdb_movie_id', b.id); else setMessage(error.message); setVersion(v => v + 1); }
  return <main className="page-content inner-page"><div className="page-title"><span className="eyebrow">KINOLOG SĄRAŠAS</span>{list ? <>{editing ? <form className="review-card list-edit" onSubmit={saveList}><label className="field">Pavadinimas<input required maxLength={80} value={editTitle} onChange={e => setEditTitle(e.target.value)} /></label><label className="field">Aprašymas<textarea maxLength={500} rows={3} value={editDescription} onChange={e => setEditDescription(e.target.value)} /></label><div className="actions"><button className="button" disabled={busy}>Išsaugoti</button><button type="button" className="button secondary" onClick={() => setEditing(false)}>Atšaukti</button></div></form> : <><h1>{list.title}</h1><p>{list.description || 'Šio sąrašo autorius dar neparašė aprašymo.'}</p></>}<small>{new Date(list.created_at).toLocaleDateString('lt-LT')} · {movies.length} filmai · {list.is_public ? 'Viešas' : 'Privatus'}</small>{list.profiles?.username && <p className="list-author">Autorius: <Link to={`/profile/${list.profiles.username}`}>{list.profiles.display_name || list.profiles.username}</Link></p>}{owner && !editing && <button className="text-button" onClick={() => setEditing(true)}>Redaguoti sąrašą</button>}</> : <p>{message || 'Kraunamas sąrašas…'}</p>}</div>{owner && <div className="add-movie"><label className="field">Pridėti filmą<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Ieškoti TMDB kataloge…" /></label>{results.length > 0 && <div className="search-results">{results.map(m => <button key={m.id} onClick={() => add(m)} disabled={busy}><span>{m.title} · {m.release_date?.slice(0,4)}</span><b>＋</b></button>)}</div>}</div>}{message && <p className="form-message" role="status">{message}</p>}{movies.length ? <div className="list-movies">{movies.map((movie,i) => <article key={movie.id} className="list-movie"><span className="position">{String(i+1).padStart(2,'0')}</span><MovieCard movie={movie} compact />{owner && <div className="reorder"><button aria-label="Perkelti aukštyn" onClick={() => shift(i,-1)} disabled={i===0}>↑</button><button aria-label="Perkelti žemyn" onClick={() => shift(i,1)} disabled={i===movies.length-1}>↓</button><button className="danger" onClick={() => remove(movie.id)}>×</button></div>}</article>)}</div> : <div className="empty"><span>▤</span><h3>Šiame sąraše filmų dar nėra</h3>{owner ? <p>Ieškok filmo viršuje ir pridėk jį prie sąrašo.</p> : <p>Filmai netrukus pasirodys.</p>}</div>}<Attribution /></main>;
}
function Profile() {
  const { username = '' } = useParams(); const { user } = useAuth(); const [profile, setProfile] = useState<{ id: string; username: string; display_name: string | null; avatar_url: string | null; bio: string | null; is_profile_public: boolean } | null>(null); const [movies, setMovies] = useState<UserMovie[]>([]); const [lists, setLists] = useState<Watchlist[]>([]); const [error, setError] = useState('');
  useEffect(() => { let live = true; (async () => { try { const client = requireSupabase(); const { data, error: e } = await client.from('profiles').select('*').eq('username', username.toLowerCase()).single(); if (e) throw e; const p = data as typeof profile & { id: string }; if (live) setProfile(p); if (!p.is_profile_public && p.id !== user?.id) { if (live) setError('Šis profilis yra privatus.'); return; } const [mr, lr] = await Promise.all([client.from('user_movies').select('*').eq('user_id', p.id).eq('status','watched').eq('is_public',true), client.from('watchlists').select('*').eq('user_id', p.id).eq('is_public',true)]); const withDetails = await Promise.all(((mr.data || []) as UserMovie[]).map(async r => { try { return { ...r, movie: await tmdb.movie(r.tmdb_movie_id) }; } catch { return r; } })); if (live) { setMovies(withDetails); setLists((lr.data || []) as Watchlist[]); } } catch (e) { if (live) setError(e instanceof Error ? e.message : 'Profilis nerastas.'); } })(); return () => { live = false; }; }, [username, user]);
  const average = movies.filter(m => m.rating).reduce((a,m) => a + (m.rating || 0),0) / (movies.filter(m => m.rating).length || 1);
  const genreCounts = new Map<string, number>(); movies.forEach(r => r.movie?.genres?.forEach(g => genreCounts.set(g.name, (genreCounts.get(g.name) || 0) + 1)));
  const topGenres = [...genreCounts.entries()].sort((a,b) => b[1]-a[1]).slice(0,3).map(([name]) => name);
  const publicMovies = movies.flatMap(r => r.movie ? [r.movie] : []);
  return <main className="page-content inner-page"><div className="profile-head"><div className="profile-avatar">{profile?.avatar_url ? <img src={profile.avatar_url} alt="" /> : (profile?.display_name || username).slice(0,1).toUpperCase()}</div><div><span className="eyebrow">KINOLOG NARYS</span><h1>{profile?.display_name || username}</h1><p>@{profile?.username || username}</p>{profile?.bio && <p className="bio">{profile.bio}</p>}</div></div>{error && <div className="state error-state">{error}</div>}<div className="stats"><div><strong>{movies.length}</strong><span>Matyti filmai</span></div><div><strong>{average.toFixed(1)}</strong><span>Vid. įvertinimas</span></div><div><strong>{lists.length}</strong><span>Vieši sąrašai</span></div></div>{topGenres.length > 0 && <section className="section"><div className="section-heading"><div><h2>Mėgstamiausi žanrai</h2><p>{topGenres.join(' · ')}</p></div></div></section>}{lists.length > 0 && <section className="section"><div className="section-heading"><div><h2>Vieši sąrašai</h2></div></div><div className="public-lists">{lists.map(l => <Link className="public-list-card" to={`/lists/${l.id}`} key={l.id}><span className="list-icon">▤</span><h3>{l.title}</h3><p>{l.description}</p></Link>)}</div></section>}{publicMovies.length > 0 && <section className="section"><div className="section-heading"><div><h2>Vieša filmų istorija</h2><p>Peržiūrėti ir viešinami filmai</p></div></div><MovieGrid movies={publicMovies} /></section>}<Attribution /></main>;
}
function SignInPrompt({ title, text }: { title: string; text: string }) { return <main className="auth-page"><section className="auth-card"><span className="brand-mark">K</span><h1>{title}</h1><p>{text}</p><Link className="button full" to={`/login?redirect=${encodeURIComponent(location.pathname)}`}>Prisijungti</Link></section></main>; }
function Attribution() { return <footer className="tmdb-attribution"><span className="tmdb-logo">TMDB</span><span>Šiame produkte naudojama TMDB API, tačiau TMDB jo nepatvirtino ir neremia.</span></footer>; }
function NotFound() { return <main className="empty not-found"><span>404</span><h1>Puslapis nerastas</h1><Link className="button" to="/">Grįžti į pradžią</Link></main>; }
function AppShell() { const { ready } = useAuth(); if (!ready) return <div className="state"><span className="spinner" />Tikrinama sesija…</div>; return <><Header /><Routes><Route path="/" element={<Home />} /><Route path="/discover" element={<Discover />} /><Route path="/movie/:id" element={<MovieDetails />} /><Route path="/library" element={<Library />} /><Route path="/lists" element={<Lists />} /><Route path="/lists/:id" element={<ListDetail />} /><Route path="/profile/:username" element={<Profile />} /> <Route path="/account" element={<AccountSettings />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Login />} /><Route path="*" element={<NotFound />} /></Routes><footer className="site-footer"><Link to="/" className="brand"><span className="brand-mark">K</span>Kino<span>Log</span></Link><span>Filmai gyvena ilgiau, kai juos prisimeni.</span><Link to="/discover">Atrasti filmus</Link></footer></>; }
export default function App() { return <BrowserRouter><AuthProvider><AppShell /></AuthProvider></BrowserRouter>; }
